MRGA. Футер, справка, создание кампании
VK-BMSTU-QA/homework-3-autumn-2023 pull request #8
Opened 2023-11-28 18:06 UTC by mmikhail2001

2023-12-13 16:31 UTC, niki-gor requested changes

2023-12-13 16:31 UTC, niki-gor commented on MRGA-Мяделец-Михаил.md
`<Команда>-<Имя>-<Фамилия>.md`
https://github.com/VK-BMSTU-QA/homework-3-autumn-2023/blob/main/README.md?plain=1#L18

2023-12-13 16:31 UTC, niki-gor commented on MRGA-Мяделец-Михаил.md
> +8. Справка. Кнопка "Кабинет партнера" редиректит на ads.vk.com/help/categories/partner
```suggestion
1. Справка. Кнопка "Авторизация" редиректит на https://ads.vk.com/help/categories/authorization
2. Справка. Кнопка "Как настроить рекламу" редиректит на https://ads.vk.com/help/categories/general
3. Справка. Кнопка "Инструменты рекламы" редиректит на https://ads.vk.com/help/categories/features
4. Справка. Кнопка "Статистика и финансы" редиректит на https://ads.vk.com/help/categories/statistics
5. Справка. Кнопка "Документы" редиректит на https://ads.vk.com/help/categories/documents
6. Справка. Кнопка "Упрощенный кабинет" редиректит на https://ads.vk.com/help/categories/mini_ads
7. Справка. Кнопка "FAQ" редиректит на https://ads.vk.com/help/categories/faq
8. Справка. Кнопка "Кабинет партнера" редиректит на https://ads.vk.com/help/categories/partner
```

2023-12-14 07:46 UTC, Yakwilik approved these changes
Аппрув

2023-12-14 09:12 UTC, niki-gor approved these changes

2023-12-14 10:36 UTC, mistergahan commented
Аппрув

2023-12-14 10:36 UTC, mistergahan approved these changes

2023-12-14 11:18 UTC, masharpik commented
апрув

2024-02-11 20:52 UTC, closed without merging